"""Graphics acceptance checks using the live probe's browser and report sink."""

def probe_graphics(browser, base_url, check, all_errors):
    context = browser.new_context(viewport={'width': 393, 'height': 851},
                                  device_scale_factor=2, is_mobile=True, has_touch=True)
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.on('console', lambda m: errors.append(m.text) if m.type == 'error' else None)
    page.goto(base_url, wait_until='networkidle')
    page.wait_for_function("typeof CORE !== 'undefined' && typeof buildSettingsUI === 'function'")
    page.evaluate('localStorage.removeItem(STORE_KEY_SETTINGS)')
    page.reload(wait_until='networkidle')
    page.click('#btn-settings')
    keys = ['enemyDetail', 'sceneryDetail', 'effects', 'ragdollQuality', 'shadowQuality', 'postProcessing']
    check('Touch graphics controls generated with auto defaults', all(page.locator('#set-'+k).input_value() == 'auto' for k in keys))
    check('Touch graphics help accessible', page.locator('#set-enemyDetail').get_attribute('aria-describedby') is not None)
    for key, value in dict(enemyDetail='detailed', sceneryDetail='detailed', effects='full', ragdollQuality='full', shadowQuality='high', postProcessing='on', quality='high').items():
        page.locator('#set-'+key).select_option(value)
    check('Model detail is safely latched until reload', page.evaluate('!graphicsAtBoot(IS_TOUCH).enemyDetailed && !graphicsAtBoot(IS_TOUCH).sceneryDetailed'))
    check('UI persists explicit touch overrides', page.evaluate("JSON.parse(localStorage.getItem(STORE_KEY_SETTINGS)).enemyDetail === 'detailed'"))
    page.reload(wait_until='networkidle')
    page.wait_for_function("assetsReady && GLB_PARSED.TREE", timeout=60000)
    check('Reload restores explicit graphics settings on touch', page.evaluate("IS_TOUCH && SETTINGS.enemyDetail === 'detailed' && graphicsAtBoot(IS_TOUCH).enemyDetailed"))
    # Keep simulation idle; manually exercising the production spawn/render paths
    # avoids depending on random wave timing or killing the player during assertions.
    detailed = page.evaluate("""() => {
      spawnEnemy(1,10,10); const en = enemies[enemies.length-1];
      const props = []; scene.traverse(o=>{if(o.userData.prop && o.isMesh)props.push(o.geometry.attributes.position.count)});
      return {soldier:!!en.parts.soldier, props:props.reduce((a,b)=>a+b,0), old:scene.children.filter(o=>o.userData.oldBarrel).length};
    }""")
    check('Explicit touch detail spawns real articulated soldier', detailed['soldier'])
    check('Explicit touch scenery replaces procedural barrels', detailed['old'] == 0 and detailed['props'] > 0)
    check('Full touch effects allocate real particles and lights', page.evaluate('PFX_ADD.cap + PFX_SMOKE.cap === 2600 && FLASH_LIGHTS.length === 2'))
    page.evaluate('fxExplosion(new THREE.Vector3(0,1,0),1); updateParticles(0.01)')
    check('Full effects emit live decorative particles', page.evaluate('PFX_ADD.alive + PFX_SMOKE.alive > 0'))
    page.evaluate("setSetting('effects','off')")
    check('Effects off retires particles, draw ranges, and flash lights', page.evaluate('PFX_ADD.cap===0 && PFX_SMOKE.cap===0 && PFX_ADD.alive===0 && PFX_SMOKE.alive===0 && PFX_ADD.geo.drawRange.count===0 && FLASH_LIGHTS.length===0'))
    page.evaluate("setSetting('effects','full')")
    check('Increasing effects does not resurrect retired particles', page.evaluate('PFX_ADD.alive===0 && PFX_SMOKE.alive===0 && !PFX_ADD.life.some(x=>x>0) && !PFX_SMOKE.life.some(x=>x>0) && FLASH_LIGHTS.length===2'))
    page.evaluate("setSetting('effects','reduced')")
    check('Reduced touch effects budget and no decorative flash lights', page.evaluate('PFX_ADD.cap+PFX_SMOKE.cap===900 && FLASH_LIGHTS.length===0'))
    page.evaluate("setSetting('effects','full'); setSetting('ragdollQuality','full'); for(let i=0;i<7;i++){spawnEnemy(1,10,10);killEnemy(enemies[enemies.length-1],false)}")
    check('Full touch ragdolls retain six actual corpses', page.evaluate('ragdollCount()===6 && RAGDOLL_BUDGET===10'))
    page.evaluate("window.retiredCorpses=ragdolls.slice(0,3).map(r=>r.en.parts.group); setSetting('ragdollQuality','reduced')")
    check('Reduced ragdolls retire oldest scene bodies live', page.evaluate('ragdollCount()===3 && retiredCorpses.every(g=>!g.parent) && RAGDOLL_BUDGET===4'))
    page.evaluate("setSetting('ragdollQuality','off'); spawnEnemy(1,10,10); const killed=enemies[enemies.length-1]; killEnemy(killed,false); window.offCorpse=killed.parts.group")
    check('Ragdolls off cleans existing and new corpse geometry', page.evaluate('ragdollCount()===0 && !offCorpse.parent'))
    page.evaluate("setSetting('ragdollQuality','full')")
    check('Ragdoll increase does not resurrect corpses', page.evaluate('ragdollCount()===0'))
    page.evaluate('renderer.render(scene,camera)')

    check('Explicit touch shadow resolution, filtering, extent and anisotropy', page.evaluate('renderer.shadowMap.enabled && renderer.shadowMap.type===graphicsShadowType("PCFSoftShadowMap") && sun.shadow.mapSize.x===2048 && SHADOW_EXTENT===38 && TEX_ALL.every(t=>t.anisotropy===Math.min(8,renderer.capabilities.getMaxAnisotropy()))'))
    page.evaluate("window.oldShadow=sun.shadow.map; window.shadowDisposed=false; oldShadow.addEventListener('dispose',()=>window.shadowDisposed=true); setSetting('shadowQuality','reduced')")
    check('Shadow resizing disposes real render target', page.evaluate('shadowDisposed && sun.shadow.map!==oldShadow && sun.shadow.mapSize.x===1024 && SHADOW_EXTENT===26 && SHADOW_ENEMY_BUDGET===4'))
    page.evaluate("setSetting('shadowQuality','off')")
    check('Shadow off disables sun and enemy casting live', page.evaluate('!renderer.shadowMap.enabled && !sun.castShadow && SHADOW_ENEMY_BUDGET===0 && enemies.every(en=>!en._castsShadow)'))
    page.evaluate("setSetting('shadowQuality','high')")
    check('Explicit shadows recover after disabling', page.evaluate('renderer.shadowMap.enabled && sun.castShadow && SHADOW_ENEMY_BUDGET===8'))
    check('Explicit touch post-processing allocates actual targets', page.evaluate('POST.enabled && !!POST.rt && POST.hdr'))
    page.evaluate("window.independentPost=POST.rt; renderer.setPixelRatio(0.8); setSetting('shadowQuality','reduced')")
    check('Shadow control preserves adaptive DPR and actual post targets', page.evaluate('renderer.getPixelRatio()===0.8 && POST.rt===independentPost'))
    page.evaluate("setSetting('shadowQuality','high'); renderer.render(scene,camera); window.independentShadow=sun.shadow.map; setSetting('postProcessing','off')")
    check('Post control preserves adaptive DPR and actual shadow target', page.evaluate('renderer.getPixelRatio()===0.8 && sun.shadow.map===independentShadow'))
    page.evaluate("setSetting('postProcessing','on')")
    check('Post enable preserves adaptive DPR and actual shadow target', page.evaluate('renderer.getPixelRatio()===0.8 && sun.shadow.map===independentShadow && POST.enabled'))
    page.evaluate("window.oldPost=POST.rt; window.postDisposed=false; oldPost.addEventListener('dispose',()=>window.postDisposed=true); setSetting('postProcessing','off')")
    check('Post-processing off disposes actual targets', page.evaluate('postDisposed && !POST.enabled && POST.rt===null'))
    page.evaluate("setSetting('quality','low'); setSetting('postProcessing','on')")
    check('Post-processing explicit on overrides low/touch automatic default', page.evaluate('POST.enabled && !!POST.rt'))
    page.evaluate("setSetting('enemyDetail','simple');setSetting('sceneryDetail','simple')")
    page.reload(wait_until='networkidle')
    page.wait_for_function('assetsReady && GLB_PARSED.TREE', timeout=60000)
    simple = page.evaluate("""() => {spawnEnemy(1,10,10); const en=enemies[enemies.length-1]; const props=[];
      scene.traverse(o=>{if(o.userData.prop && o.isMesh)props.push(o.geometry.attributes.position.count)});
      return {simple:!en.parts.soldier,props:props.reduce((a,b)=>a+b,0),old:scene.children.filter(o=>o.userData.oldBarrel).length};}""")
    check('Simple mode spawns lightweight enemies with assets available', simple['simple'])
    check('Simple scenery retains barrels and cheaper actual geometry', simple['old'] == 16 and simple['props'] < detailed['props'])
    page.evaluate("setSetting('ragdollQuality','full'); killEnemy(enemies[enemies.length-1],false); window.simpleGeometryTotal=0; window.simpleGeometryDisposed=0; const owned=new Set(); for(const r of ragdolls){r.en.parts.group.traverse(o=>{if(o.geometry)owned.add(o.geometry)}); for(const p of r.boxParts||[])p.obj.traverse(o=>{if(o.geometry)owned.add(o.geometry)})} window.simpleGeometryTotal=owned.size; for(const g of owned)g.addEventListener('dispose',()=>window.simpleGeometryDisposed++); setSetting('ragdollQuality','off')")
    check('Simple corpse retirement disposes every detached and retained geometry', page.evaluate('simpleGeometryTotal>0 && simpleGeometryDisposed>=simpleGeometryTotal && ragdollCount()===0'))
    page.click('#btn-settings')
    page.locator('#set-postProcessing').scroll_into_view_if_needed()
    check('Last graphics control remains reachable on mobile', page.locator('#set-postProcessing').is_visible())
    page.click('#btn-settings-reset')
    check('Reset restores all six auto choices in actual UI', all(page.locator('#set-'+k).input_value() == 'auto' for k in keys))
    check('Reset persists defaults', page.evaluate('JSON.parse(localStorage.getItem(STORE_KEY_SETTINGS)).postProcessing === "auto"'))
    page.reload(wait_until='networkidle')
    check('Reset reload restores conservative touch graphics', page.evaluate('!graphicsAtBoot(IS_TOUCH).enemyDetailed && graphicsNow().particles===900 && !POST.enabled'))
    page.evaluate("localStorage.setItem(STORE_KEY_SETTINGS, JSON.stringify({quality:'high',effects:'bogus',enemyDetail:'invalid'}))")
    page.reload(wait_until='networkidle')
    check('Old and invalid saved graphics settings sanitize in browser', page.evaluate("SETTINGS.enemyDetail==='auto' && SETTINGS.effects==='auto' && SETTINGS.shadowQuality==='auto' && SETTINGS.quality==='high'"))
    check('Graphics browser switching/reload produces no errors', not errors, '\n'.join(errors))
    all_errors.extend(errors)
    context.close()
    blocked = browser.new_context(viewport={'width':393,'height':851},is_mobile=True,has_touch=True)
    blocked.add_init_script("Storage.prototype.getItem = Storage.prototype.setItem = Storage.prototype.removeItem = function(){throw new Error('storage unavailable')}")
    page = blocked.new_page(); storage_errors=[]
    page.on('pageerror', lambda e: storage_errors.append(str(e)))
    page.goto(base_url,wait_until='networkidle')
    page.click('#btn-settings'); page.locator('#set-effects').select_option('full')
    check('Unavailable storage still permits usable live graphics UI', page.evaluate("SETTINGS.effects==='full' && PFX_ADD.cap+PFX_SMOKE.cap===2600"))
    page.click('#btn-settings-reset')
    check('Unavailable storage reset works without exception', page.evaluate("SETTINGS.effects==='auto'") and not storage_errors)
    all_errors.extend(storage_errors); blocked.close()
